# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x64\x64ressbook.proto\x12\x12\x63om.example.protos\"\xb0\x02\n\x06Person\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05\x65mail\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x36\n\x06phones\x18\x04 \x03(\x0b\x32&.com.example.protos.Person.PhoneNumber\x1ao\n\x0bPhoneNumber\x12\x13\n\x06number\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x37\n\x04type\x18\x02 \x01(\x0e\x32$.com.example.protos.Person.PhoneTypeH\x01\x88\x01\x01\x42\t\n\x07_numberB\x07\n\x05_type\"+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02\x42\x05\n\x03_idB\x07\n\x05_nameB\x08\n\x06_email\"9\n\x0b\x41\x64\x64ressBook\x12*\n\x06people\x18\x01 \x03(\x0b\x32\x1a.com.example.protos.PersonB)\n\x12\x63om.example.protosB\x11\x41\x64\x64ressBookProtosP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addressbook_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022com.example.protosB\021AddressBookProtosP\001'
  _globals['_PERSON']._serialized_start=42
  _globals['_PERSON']._serialized_end=346
  _globals['_PERSON_PHONENUMBER']._serialized_start=164
  _globals['_PERSON_PHONENUMBER']._serialized_end=275
  _globals['_PERSON_PHONETYPE']._serialized_start=277
  _globals['_PERSON_PHONETYPE']._serialized_end=320
  _globals['_ADDRESSBOOK']._serialized_start=348
  _globals['_ADDRESSBOOK']._serialized_end=405
# @@protoc_insertion_point(module_scope)
